### ISSUE TITLE
Support for controlling debounce time

### ISSUE THREAD

**Issue by jooj123** [Merri/react-lazy#17]
Seems you cant control the debounce time of via a prop: https://github.com/Merri/react-lazy/blob/889e7afedab4e051219242f3583ebc0ce787632d/src/lib/viewport.js#L81 (hard coded at 50)

Probably should be exposed as sometimes you want it to be higher / lower depending on use case.

I know you can use this method: https://github.com/Merri/react-lazy#checkelementsinviewport but this seems a bit clunky, should be an exposed prop instead

I am happy to throw up a PR if you think this sounds reasonable

**Comment by Merri** [comment]
I guess the main issue is that this is currently a global setting: it will have effect on all components and all calls to `checkElementsInViewport` at once, which means mixed use cases would conflict. The reason for having just one method for the job has been performance (minimize use of event listeners and memory).

The problem is that if you add config option on component basis you end up with a lot of event listeners (one per component), unless you do some clever coding. One way to limit this is to provide something like a function to generate a component which instances share the same config and thus use the same set of event listeners (instead each having it's own set of those).

There is also the question whether some people would want to use throttle instead. Also, someone might want to customize which `window` events should be listened to. Doing these would sacrifice some simplicity of the current component for giving power for further configuration and customization.

**Comment by ccheney** [comment]
Thoughts on an option to throttle instead of debounce? (slightly off topic)

**Comment by dpuscher** [comment]
I added the `throttle` method some months ago and also made the hard coded 50ms debounce time adjustable by using a setting. Unfortunately the PR still got no feedback... 🤔

**Comment by Merri** [comment]
v1.0.0 with IntersectionObserver has been released, which removes this issue entirely.
